!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2)
!     It contains Fortran 90 wrappers to fortran functions.

      
      subroutine f2pyinitsystem(f2pysetupfunc)
      use system, only : beta
      use system, only : mass
      use system, only : mode
      use system, only : max_atoms
      use system, only : dt
      use system, only : pi
      use system, only : thermostat
      use system, only : andersen_sampling_time
      use system, only : max_gle_ns
      use system, only : gle_ns
      use system, only : gle_a
      use system, only : gle_c
      use system, only : equilibrate
      use system, only : recrossing_trajectory
      use system, only : umbrella_trajectory
      use system, only : verlet_step
      use system, only : free_ring_polymer_step
      use system, only : constrain_to_dividing_surface
      use system, only : constrain_momentum_to_dividing_surface
      use system, only : add_umbrella_potential
      use system, only : add_bias_potential
      use system, only : get_reaction_coordinate
      use system, only : get_recrossing_flux
      use system, only : get_recrossing_velocity
      use system, only : sample_momentum
      use system, only : get_ring_polymer_energy
      use system, only : get_kinetic_energy
      use system, only : get_center_of_mass
      use system, only : get_centroid
      use system, only : get_radius_of_gyration
      use system, only : update_vmd_output
      external f2pysetupfunc
      call f2pysetupfunc(beta,mass,mode,max_atoms,dt,pi,thermostat,ander&
     &sen_sampling_time,max_gle_ns,gle_ns,gle_a,gle_c,equilibrate,recros&
     &sing_trajectory,umbrella_trajectory,verlet_step,free_ring_polymer_&
     &step,constrain_to_dividing_surface,constrain_momentum_to_dividing_&
     &surface,add_umbrella_potential,add_bias_potential,get_reaction_coo&
     &rdinate,get_recrossing_flux,get_recrossing_velocity,sample_momentu&
     &m,get_ring_polymer_energy,get_kinetic_energy,get_center_of_mass,ge&
     &t_centroid,get_radius_of_gyration,update_vmd_output)
      end subroutine f2pyinitsystem

      subroutine f2pywrap_transition_state_evaluate_all (position, natom&
     &s, values, f2py_values_d0, f2py_values_d1)
      use transition_state, only : evaluate_all
      integer natoms
      integer f2py_values_d0
      integer f2py_values_d1
      double precision position(3,natoms)
      double precision values(f2py_values_d0,f2py_values_d1)
      call evaluate_all(position, natoms, values)
      end subroutine f2pywrap_transition_state_evaluate_all
      
      subroutine f2pyinittransition_state(f2pysetupfunc)
      use transition_state, only : max_ts
      use transition_state, only : max_atoms
      use transition_state, only : number_of_bonds
      use transition_state, only : forming_bond_lengths
      use transition_state, only : breaking_bond_lengths
      use transition_state, only : max_bonds
      use transition_state, only : number_of_transition_states
      use transition_state, only : breaking_bonds
      use transition_state, only : forming_bonds
      use transition_state, only : value
      use transition_state, only : gradient
      use transition_state, only : hessian
      use transition_state, only : evaluate
      interface 
      subroutine f2pywrap_transition_state_evaluate_all (position, natom&
     &s, values, f2py_values_d0, f2py_values_d1)
      integer natoms
      integer f2py_values_d0
      integer f2py_values_d1
      double precision position(3,natoms)
      double precision values(f2py_values_d0,f2py_values_d1)
      end subroutine f2pywrap_transition_state_evaluate_all
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(max_ts,max_atoms,number_of_bonds,forming_bond_l&
     &engths,breaking_bond_lengths,max_bonds,number_of_transition_states&
     &,breaking_bonds,forming_bonds,f2pywrap_transition_state_evaluate_a&
     &ll,value,gradient,hessian,evaluate)
      end subroutine f2pyinittransition_state

      
      subroutine f2pyinitreactants(f2pysetupfunc)
      use reactants, only : nreactant1_atoms
      use reactants, only : reactant1_atoms
      use reactants, only : massfrac
      use reactants, only : nreactant2_atoms
      use reactants, only : max_atoms
      use reactants, only : rinf
      use reactants, only : reactant2_atoms
      use reactants, only : reactant1_center_of_mass
      use reactants, only : reactant2_center_of_mass
      use reactants, only : value
      use reactants, only : gradient
      use reactants, only : hessian
      use reactants, only : evaluate
      external f2pysetupfunc
      call f2pysetupfunc(nreactant1_atoms,reactant1_atoms,massfrac,nreac&
     &tant2_atoms,max_atoms,rinf,reactant2_atoms,reactant1_center_of_mas&
     &s,reactant2_center_of_mass,value,gradient,hessian,evaluate)
      end subroutine f2pyinitreactants


